version: '3'
services:
  postgres:
    image: postgres:13
    ports:
        - 5432:5432
    volumes:
        - db-data-auth:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  auth:
    image: hicsail/auth:unstable
    restart: always
    depends_on:
      - postgres
    ports:
      - 3001:3000

volumes:
  db-data-auth:
